# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 17:12
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='encode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldname', models.CharField(max_length=12)),
                ('newname', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Filedownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=app.models.get_file_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
