# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='encode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldname', models.CharField(max_length=12)),
                ('newname', models.CharField(max_length=2)),
            ],
        ),
    ]
