# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0002_encode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Fileupload',
        ),
    ]
