# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0003_auto_20160823_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filedownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
